require('./config/config');
var {mongoose} = require('./db/mongoose');
var {Student} = require('./models/student');

let students = [
"Jack Slusser",
"Jasmine Pesis",
"Hannah Vecchiarelli",
"Cameron Murray",
"Kellen Kao",
"Xander Matcuk",
"Luka Semchyshyn",
"Charlie Macleod",
"Henry King",
"Jack Kwon",
"Angelina Tsuboi",
"Ruben Gallegos",
"Sidney Friedrich",
"Jayme Mow",
"Liya Bhakta",
"Ryan Rubin",
"Kai Fang",
"Shane Cartwright",
"Charlie Landsberg",
"Brian Smith",
"Evan Kaufman",
"Maxwell Busse",
"Lauryn Hachiya",
"Nolan Bowen",
"Keifer Menchaca",
"Ronan mullins",
"Julian Kuhr",
"Emiliano Ramirez",
"Jackson Scott",
"Bob Sheen",
"Livia Tseng",
"Leon Tsuboi",
"Hudson Trieu",
"William Stanton",
"Kieran Bowen",
"Lila Schroeder",
"Kiora Lu",
"Benjamin Penny",
"Jamie Pivaral",
"Harris Stockton",
"Lindsey Yamashiro",
"Skylar Harris",
"Jason Agus",
"Armaan Arora",
"Justin Wang",
"Evan Le",
"Kaylee Mizufuka",
"Aaron Peltz",
"Nelson Rios Jr",
"Erika Fake",
"Eric Escalante",
"Mason Trieu",
"Alex Sun",
"Tristan Creamer",
"Tyler Cipriano",
"Brian Murphy",
"Sam Khaleghian",
"Maxwell Stahl",
"Romeo Tsuboi",
"Suede Solomon",
"Haruyuki Miyoshi",
"Luna Zhang",
"Erika Alexander",
"Max Waldman",
"Mark Liu",
"Jack Pierse",
"Gigi Gallemore",
"sidney test",
"Noe Brennan",
"Jet Pham",
"Tyler Germain",
"Dylan Moulthrop",
"Skyler Gordon",
"Aidan Phan",
"Matthew Baker",
"Charlotte Meyen",
"Adam Truong",
"Jeremiah St. Pierre",
"Logan Elliott",
"Vasco Visentin",
"Bella Derbyshire",
"Jacob Chu",
"Julia Delaney",
"Tristin Kapanke",
"Ashton Ludwig",
"Jeffry Alvarado",
"Yuji Wexler",
"Kingston Duron",
"Lucas Pearce",
"Ella Slezak",
"Jake Yun",
"Zavier Severin",
"Evan Lee",
"Jett Do",
"Brandon Le",
"Sullivan Daily",
"Zoran Malis",
"Jax Pham",
"Joshua Mow",
"Zeb Brennan",
"kmals",
"Griffin Galimi",
"Harrison George Haymons",
"Wyatt Newbill",
"Conor Mullins",
"Sawyer Alonso",
"Ethan Chun",
"Eli Hill",
"Frank Wong",
"William Truong",
"Leo Tseng",
"Colette Kim",
"Aanav Patel",
"Brad Croft",
"Shivana Parekh",
"Makaila Reese",
"Aiden Lopez",
"Allen Liu",
"Sidney Nemzer",
"Jeremy Leopard",
"Anastasia Davydova Lewis",
"Gannon Jacobson",
"Tibet Taciroglu",
"James O'deegan",
"Micah Chu",
"Tiger Gallemore",
"Jack Ireland",
"Jake Brandon",
"Jana Meyen",
"Joy Serquina",
"Griffin Tyndorf",
"Priya Munot",
"Hunter Ki Kim",
"Jason Tran",
"Devyn Graeler",
"Aiden Kellerman",
"kma",
"Sofia Goldsten",
"Nicholas Harris",
"Erik",
"Taylor Vickerman",
"Landon Frank",
"Neftaly",
"Alex",
"Arianna Matcuk",
"Max Zamarni",
"James Caldwell",
]

const insertStudents = async ()=>{
    for(let i = 0; i < students.length; i++)
    {
        let student = new Student({name:students[i]});

        await student.save();
    }
}

// insertStudents();

module.exports = {
    insertStudents: insertStudents
}